pool:
 vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  displayName: Set dotnet core version
  inputs:
   version: '6.0.x'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
   command: build
   projects: '**/*.csproj'
   arguments: '--configuration $(buildConfiguration)'
- script: dotnet publish -c Release -o build /
p:PackageAsSingleFile=true
 displayName: Publish

- script: tar -a -c -C build -f Application.zip *.* 
  displayName: Zip

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
   azureSubscription: 'Pay-As-You-Go'
   appName: devtestweb
   appType: webApp
   package: ./**/*.zip
