name: publish 
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: gitacdevweb
  AZURE_DEVWEBAPP_NAME: GitAc-Dev
  AZURE_PREPRODWEBAPP_NAME: GitAc-PreProd
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
 
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: restore
        run: dotnet restore ./deploynet.csproj
      
      - name: build
        run: dotnet build ./deploynet.csproj --configuration Release --no-restore
      
      - name: publish
        run: dotnet publish ./deploynet.csproj --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

        
#       - name: Deploy to IIS
#         uses: warrenbuckley/DeployIISWebsite@master
#         with:
#           websiteName: gitacdevweb
#           webDeployPackage: '${{ github.workflows }}/publish'

#         env:
#           SERVER: 'http://localhost:80'

  DeployDev:
      
      name: Deployment
      if: github.event_name == 'refs/heads/master'
      needs: publish
      runs-on: ubuntu-latest
      environment:
        name: Dev
      steps:
        - name: Deploy
          uses: Azure/webapps-deploy@v2
          with:
              app-name: ${{env.AZURE_DEVWEBAPP_NAME}}
              publish-profile: ${{secrets.AZURE_DEVPUBLISH_PROFILE}}
              package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
