name: publish 
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: gitacdevweb
  AZURE_WEBAPP_PACKAGE_PATH: "${{ github.workflows }}/publish" 
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: restore
        run: dotnet restore ./deploynet.csproj
      
      - name: build
        run: dotnet build ./deploynet.csproj --configuration Release --no-restore
      
      - name: publish
        run: dotnet publish ./deploynet.csproj --configuration Release --no-build
        
#       - name: Deploy to IIS
#         uses: warrenbuckley/DeployIISWebsite@master
#         with:
#           websiteName: gitacdevweb
#           webDeployPackage: '${{ github.workflows }}/publish'

#         env:
#           SERVER: 'http://localhost:80'

      - name: Deployment
        uses: actions/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{AZURE_WEBAPP_PACKAGE_PATH}}"
